db_adminuser: 'postgres'
db_adminpass: 
db_user: 'botomod'
db_pass: 
db_hostname: 'localhost'
db_port: '5432'
db_name: 'ayy'


watched_subreddits:
  - cats

do_not_scan_users:
  - automoderator


report_subs:
  - reportedsub
filter_subs:
  - filteredsub
remove_subs:
  - removedsub



report_desc:
  - ''
filter_desc:
  - '.nlyf.ns'
remove_desc:
  - ''